# Generated by Django 4.2.25 on 2025-10-23 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "بازدید صفحه",
                "verbose_name_plural": "بازدیدهای صفحه",
                "ordering": ["-visited_at"],
            },
        ),
        migrations.CreateModel(
            name="SignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام کامل"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تلفن باید با 09 شروع شود و 11 رقم باشد",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("TEHRAN", "تهران"),
                            ("MASHHAD", "مشهد"),
                            ("ISFAHAN", "اصفهان"),
                            ("SHIRAZ", "شیراز"),
                            ("TABRIZ", "تبریز"),
                            ("KARAJ", "کرج"),
                            ("AHVAZ", "اهواز"),
                            ("QOM", "قم"),
                            ("KERMANSHAH", "کرمانشاه"),
                            ("URMIA", "ارومیه"),
                            ("RASHT", "رشت"),
                            ("ZAHEDAN", "زاهدان"),
                            ("KERMAN", "کرمان"),
                            ("YAZD", "یزد"),
                            ("ARAK", "اراک"),
                            ("ARDABIL", "اردبیل"),
                            ("BANDAR_ABBAS", "بندر عباس"),
                            ("ESLAMSHAHR", "اسلامشهر"),
                            ("ZANJAN", "زنجان"),
                            ("SANANDAJ", "سنندج"),
                            ("KHORRAMABAD", "خرم\u200cآباد"),
                            ("GORGAN", "گرگان"),
                            ("SARI", "ساری"),
                            ("DEZFUL", "دزفول"),
                            ("SAVEH", "ساوه"),
                            ("BOJNURD", "بجنورد"),
                            ("OTHER", "سایر شهرها"),
                        ],
                        max_length=50,
                        verbose_name="شهر",
                    ),
                ),
                (
                    "fitness_goal",
                    models.CharField(
                        choices=[
                            ("WEIGHT_LOSS", "کاهش وزن"),
                            ("MUSCLE_GAIN", "افزایش عضله"),
                            ("GENERAL_FITNESS", "تناسب عمومی"),
                            ("ENDURANCE", "استقامت"),
                            ("FLEXIBILITY", "انعطاف\u200cپذیری"),
                        ],
                        max_length=50,
                        verbose_name="هدف شما",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "کاربر (دانشجو)"),
                            ("COACH", "مربی"),
                            ("DIETITIAN", "متخصص تغذیه"),
                            ("GYM", "باشگاه"),
                        ],
                        max_length=20,
                        verbose_name="نقش شما",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل (اختیاری)",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False, verbose_name="موافقت با دریافت اطلاعات"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "utm_source",
                    models.CharField(blank=True, max_length=100, verbose_name="منبع"),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, max_length=100, verbose_name="رسانه"),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=100, verbose_name="کمپین"),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="معتبر است"),
                ),
                (
                    "is_contacted",
                    models.BooleanField(default=False, verbose_name="تماس گرفته شده"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت\u200cها")),
            ],
            options={
                "verbose_name": "ثبت\u200cنام",
                "verbose_name_plural": "ثبت\u200cنام\u200cها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number"], name="landing_sig_phone_n_89efc1_idx"
                    ),
                    models.Index(fields=["city"], name="landing_sig_city_69cd0e_idx"),
                    models.Index(fields=["role"], name="landing_sig_role_c7d05c_idx"),
                    models.Index(
                        fields=["created_at"], name="landing_sig_created_20f7d4_idx"
                    ),
                ],
            },
        ),
    ]
